#!/usr/bin/env bats
# Tests for bin/compress.sh — session digest from agents.jsonl.

setup() {
  SCRIPT="$BATS_TEST_DIRNAME/../../bin/compress.sh"
  [ -f "$SCRIPT" ] || skip "script not found: $SCRIPT"
  TMPD="$(mktemp -d)"
  FIXTURE="$TMPD/agents.jsonl"
}

teardown() {
  [ -n "${TMPD:-}" ] && rm -rf "$TMPD"
}

@test "exits 2 when no input given" {
  run bash "$SCRIPT"
  [ "$status" -eq 2 ]
  [[ "$output" == *"usage:"* ]]
}

@test "exits 1 on missing input file" {
  run bash "$SCRIPT" "$TMPD/does-not-exist.jsonl"
  [ "$status" -eq 1 ]
  [[ "$output" == *"not found"* ]]
}

@test "graceful message when input is empty" {
  echo "" > "$FIXTURE"
  run bash "$SCRIPT" "$FIXTURE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"empty input"* ]]
}

@test "renders header with line count and timestamps" {
  cat > "$FIXTURE" <<'EOF'
{"ts":"2026-05-04T10:00:00Z","epoch":1746360000,"event":"post","tool":"Task","agent":"strategist","desc":"x","duration":60}
{"ts":"2026-05-04T10:05:00Z","epoch":1746360300,"event":"post","tool":"Task","agent":"architect","desc":"y","duration":120}
EOF
  run bash "$SCRIPT" "$FIXTURE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Session digest"* ]]
  [[ "$output" == *"Lines: 2"* ]]
  [[ "$output" == *"2026-05-04T10:00:00Z"* ]]
}

@test "renders Agents section ranked by invocation count" {
  cat > "$FIXTURE" <<'EOF'
{"ts":"2026-05-04T10:00:00Z","epoch":1746360000,"event":"post","tool":"Task","agent":"frequent","desc":"a","duration":10}
{"ts":"2026-05-04T10:01:00Z","epoch":1746360060,"event":"post","tool":"Task","agent":"frequent","desc":"b","duration":15}
{"ts":"2026-05-04T10:02:00Z","epoch":1746360120,"event":"post","tool":"Task","agent":"frequent","desc":"c","duration":20}
{"ts":"2026-05-04T10:03:00Z","epoch":1746360180,"event":"post","tool":"Task","agent":"rare","desc":"d","duration":5}
EOF
  run bash "$SCRIPT" "$FIXTURE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Agents (ranked"* ]]
  # frequent should appear before rare
  freq_pos=$(echo "$output" | grep -n "frequent" | tail -1 | cut -d: -f1)
  rare_pos=$(echo "$output" | grep -n "rare" | tail -1 | cut -d: -f1)
  [ "$freq_pos" -lt "$rare_pos" ]
}

@test "renders Bash section with command frequencies" {
  cat > "$FIXTURE" <<'EOF'
{"ts":"2026-05-04T10:00:00Z","epoch":1746360000,"event":"post","tool":"Bash","cmd":"git status"}
{"ts":"2026-05-04T10:01:00Z","epoch":1746360060,"event":"post","tool":"Bash","cmd":"git status"}
{"ts":"2026-05-04T10:02:00Z","epoch":1746360120,"event":"post","tool":"Bash","cmd":"npm test"}
EOF
  run bash "$SCRIPT" "$FIXTURE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Bash commands"* ]]
  [[ "$output" == *"git status"* ]]
}

@test "reads from stdin when arg is '-'" {
  data='{"ts":"2026-05-04T10:00:00Z","epoch":1746360000,"event":"post","tool":"Task","agent":"strategist","desc":"x","duration":60}'
  run bash -c "echo '$data' | bash '$SCRIPT' -"
  [ "$status" -eq 0 ]
  [[ "$output" == *"strategist"* ]]
}

@test "ignores Bash and unknown agents from Agents section" {
  cat > "$FIXTURE" <<'EOF'
{"ts":"2026-05-04T10:00:00Z","epoch":1746360000,"event":"post","tool":"Bash","agent":"Bash","cmd":"x"}
{"ts":"2026-05-04T10:01:00Z","epoch":1746360060,"event":"post","tool":"Task","agent":"unknown","desc":"y"}
{"ts":"2026-05-04T10:02:00Z","epoch":1746360120,"event":"post","tool":"Task","agent":"valid-agent","desc":"z","duration":30}
EOF
  run bash "$SCRIPT" "$FIXTURE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"valid-agent"* ]]
  # Should NOT have an agents-table row for "Bash" or "unknown"
  ! echo "$output" | grep -qE '^\| `Bash` \|'
  ! echo "$output" | grep -qE '^\| `unknown` \|'
}

@test "includes timestamp in footer" {
  cat > "$FIXTURE" <<'EOF'
{"ts":"2026-05-04T10:00:00Z","epoch":1746360000,"event":"post","tool":"Task","agent":"x","desc":"y","duration":60}
EOF
  run bash "$SCRIPT" "$FIXTURE"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Generated by"* ]]
  [[ "$output" == *"compress.sh"* ]]
}
